"""changes

Revision ID: 2c592d3a12ff
Revises:
Create Date: 2024-08-15 00:03:40.437979

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2c592d3a12ff"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reservation", schema=None) as batch_op:
        batch_op.add_column(sa.Column("total_price", sa.Float(), nullable=False))
        batch_op.drop_column("start_at")
        batch_op.drop_column("total")

    with op.batch_alter_table("showtime", schema=None) as batch_op:
        batch_op.add_column(sa.Column("start_time", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("end_time", sa.DateTime(), nullable=False))
        batch_op.drop_column("start_date")
        batch_op.drop_column("end_date")

    with op.batch_alter_table("theatre", schema=None) as batch_op:
        batch_op.drop_column("ticket_price")
        batch_op.drop_column("image")
        batch_op.drop_column("city")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("theatre", schema=None) as batch_op:
        batch_op.add_column(sa.Column("city", sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column("image", sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(
            sa.Column(
                "ticket_price",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("showtime", schema=None) as batch_op:
        batch_op.add_column(sa.Column("end_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(
            sa.Column(
                "start_date",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("end_time")
        batch_op.drop_column("start_time")

    with op.batch_alter_table("reservation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "total",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("start_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column("total_price")

    # ### end Alembic commands ###
